apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dax-uploads-pvc
  namespace: dax-autolabeling
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # storageClassName: <your-storage-class>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dax-sqlite-pvc
  namespace: dax-autolabeling
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: <your-storage-class>
