apiVersion: v1
kind: Secret
metadata:
  name: dax-secrets
  namespace: dax-autolabeling
type: Opaque
stringData:
  # Change this in real environments
  sessionSecret: "CHANGE_ME_TO_A_LONG_RANDOM_STRING"

